<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>6d3109d3-6ff5-438e-aa23-cddd3703b4cb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Agents.Persistent" Version="1.1.0" />
    <PackageReference Include="Azure.Identity" Version="1.16.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.9" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.65.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.65.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" Version="1.65.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.9" />
  </ItemGroup>


</Project>
